name: DSF 2.x Full Build

on:
  pull_request:
    branches: [main, develop]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  maven-quick-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
          cache: 'maven'
      - name: Minimal Maven Build
        run: mvn install --batch-mode --fail-at-end -P!generate-source-and-javadoc-jars -Dimpsort.skip=true -Dformatter.skip=true -Dlicense.skip=true -Denforcer.skip -DskipTests -Dmaven.buildNumber.skip=true -Denforcer.skip -DskipShadePlugin=true
      - name: Upload quick-build results
        uses: actions/upload-artifact@v6
        with:
          name: quick_build
          path: |
            ./**/target
            dsf-docker/bpe_proxy/ca/client_ca_chains/*.crt
            dsf-docker/bpe_proxy/ca/client_issuing_cas/*.crt
            dsf-docker/fhir_proxy/ca/client_ca_chains/*.crt
            dsf-docker/fhir_proxy/ca/client_issuing_cas/*.crt
            dsf-bpe/dsf-bpe-server-jetty/docker/api/v1/*.jar
            dsf-bpe/dsf-bpe-server-jetty/docker/api/v2/*.jar
            dsf-bpe/dsf-bpe-server-jetty/docker/ca/client_ca_chains/*.crt
            dsf-bpe/dsf-bpe-server-jetty/docker/ca/server_root_cas/*.crt
            dsf-bpe/dsf-bpe-server-jetty/docker/lib/*.jar
            dsf-bpe/dsf-bpe-server-jetty/docker/dsf_bpe.jar
            dsf-fhir/dsf-fhir-server-jetty/docker/ca/client_ca_chains/*.crt
            dsf-fhir/dsf-fhir-server-jetty/docker/ca/server_root_cas/*.crt
            dsf-fhir/dsf-fhir-server-jetty/docker/lib/*.jar
            dsf-fhir/dsf-fhir-server-jetty/docker/dsf_fhir.jar

  proxy-docker-build:
    # if: github.event.pull_request.merged == true
    if: false
    runs-on: ubuntu-latest
    needs: maven-quick-build
    permissions:
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: bpe_proxy
            context: dsf-docker/bpe_proxy
          - name: fhir_proxy
            context: dsf-docker/fhir_proxy
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v6
      - name: Download quick-build results
        uses: actions/download-artifact/@v7
        with:
          name: quick_build
          path: ./
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:develop
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ matrix.image.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image.name }}
      - name: Export digest
        run: echo "DIGEST=${{ steps.push.outputs.digest }}" >> $GITHUB_ENV
      - name: Set up syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Generate SBOM
        run: syft ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST} -o cyclonedx-json > sbom.json
      - name: Set up cosign
        uses: sigstore/cosign-installer@v3
      - name: Attach SBOM
        run: cosign attest --yes --predicate sbom.json --type cyclonedx ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST}
      - name: Sign image
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST}

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin', 'javascript-typescript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
          cache: 'maven'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          queries: security-extended, security-and-quality
      - name: Minimal Maven Build
        run: mvn package --batch-mode --fail-at-end -P!generate-source-and-javadoc-jars -Dimpsort.skip=true -Dformatter.skip=true -Dlicense.skip=true -Denforcer.skip -DskipTests -Dmaven.buildNumber.skip=true -Denforcer.skip -DskipShadePlugin=true
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"

  trivy:
    runs-on: ubuntu-latest
    needs: maven-quick-build
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: bpe_proxy
            context: dsf-docker/bpe_proxy
          - name: fhir_proxy
            context: dsf-docker/fhir_proxy
          - name: bpe
            context: dsf-bpe/dsf-bpe-server-jetty/docker
          - name: fhir
            context: dsf-fhir/dsf-fhir-server-jetty/docker
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v6
      - name: Download quick-build results
        uses: actions/download-artifact/@v7
        with:
          name: quick_build
          path: ./
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run:  docker build -t ${{ matrix.image.name }}:${{ github.sha }} ${{ matrix.image.context }}
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ matrix.image.name }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

  maven-full-build:
    runs-on: ubuntu-latest
    needs: maven-quick-build
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v6
      - name: Download quick-build results
        uses: actions/download-artifact/@v7
        with:
          name: quick_build
          path: ./
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25
          cache: 'maven'
      - name: Full Maven Build
        run: mvn install --batch-mode --fail-at-end -DforkCount=2

  docker-build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [maven-quick-build, maven-full-build, codeql]
    permissions:
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: bpe
            context: dsf-bpe/dsf-bpe-server-jetty/docker
          - name: fhir
            context: dsf-fhir/dsf-fhir-server-jetty/docker
          - name: bpe_proxy
            context: dsf-docker/bpe_proxy
          - name: fhir_proxy
            context: dsf-docker/fhir_proxy
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v6
      - name: Download quick-build results
        uses: actions/download-artifact/@v7
        with:
          name: quick_build
          path: ./
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:develop
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ matrix.image.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.image.name }}
      - name: Export digest
        run: echo "DIGEST=${{ steps.push.outputs.digest }}" >> $GITHUB_ENV
      - name: Set up syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Generate SBOM
        run: syft ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST} -o cyclonedx-json > sbom.json
      - name: Set up cosign
        uses: sigstore/cosign-installer@v3
      - name: Attach SBOM
        run: cosign attest --yes --predicate sbom.json --type cyclonedx ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST}
      - name: Sign image
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}@${DIGEST}
